### ISSUE TITLE
desktop-file-service: doesn't properly watch applications directories on NixOS

### ISSUE THREAD

**Issue by worldofpeace** [elementary/applications-menu#182]
### Expected Behavior

Anytime I add or remove an application from my system the application menu should reflect that.

### Current Behavior
On [NixOS](https://nixos.org) any application that is installed into the system environment that has a
`share/` directory gets added to the `XDG_DATA_DIRS` environment variable.

So take note that it will be populated with a bunch of absolute paths, possibly symlinks, and anytime the system is rebuilt paths will be changed and **added**.

I don't think the current `desktop-file-service` can properly watch those changes, as anytime a new application is installed (new path added to XDG_DATA_DIRS) it doesn't update.

This requires our users to log out and log in to see the appropriate effect.

**Comment by worldofpeace** [comment]
cc @davidak (they probably can reproduce this)

**Comment by davidak** [comment]
I had that issue in the past and can try to reproduce it with the latest versions.

**Comment by davidak** [comment]
I just installed darktable and it did not appear in the menu. It was present after reboot.

---

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.59, NixOS, 19.03.173165.55b8860aa20 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(davidak): `""`
 - channels(root): `"nixos-19.03.173165.55b8860aa20, nixos-hardware, nixos-unstable-19.09pre185259.362be9608c3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
I believe if whatever library applications-menu uses stops following symlinks this should be resolved.

**Comment by davidmhewitt** [comment]
I'd be interested to hear if #451 helps with this

**Comment by davidmhewitt** [comment]
On second thoughts, it might not help with stuff appearing in the menu when you're "browsing". We have the same problem when you install a Flatpak for the very first time and my branch only fixes searching for it, not browsing for it.

I'll be following up with more fixes soon anyway...

**Comment by worldofpeace** [comment]
> On second thoughts, it might not help with stuff appearing in the menu when you're "browsing". We have the same problem when you install a Flatpak for the very first time and my branch only fixes searching for it, not browsing for it.
> 
> I'll be following up with more fixes soon anyway...

Always nice to see 10 elseif's die :grin: 
I think it's likely that any of those fixes you make will improve the situation, I could test again when you submit new fixes :+1:

**Comment by davidak** [comment]
I can still reproduce the issue that newly installed programs are not listed on the menu.

For example i installed vlc. But it does show up in the search now like this:

![Screenshot from 2021-08-22 01-26-55](https://user-images.githubusercontent.com/91113/130337262-74973871-2d61-4e4e-939b-dccef966dbd9.png)

NixOS 21.11.git.2df0402e4bb, with elementary 6 (WIP)
